{% set version = "v3.2.0" %}
{% set sha256 = "c53206eeb1b78259ac0b77a5f555ed6d5919abddb30fc164c4a631a33c8006bb" %}

package:
  name: hhsuite
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/soedinglab/hh-suite/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openmp
    - perl
    - python
  run:
    - openmp
    - python
    - perl

test:
  commands:
    - hhblits -h > /dev/null
    - hhsearch -h > /dev/null
    - hhalign -h > /dev/null

about:
  home: https://github.com/soedinglab/hh-suite
  license: GPLv3
  license_file: LICENSE
  summary: "HH-suite3 for fast remote homology detection and deep protein annotation"
