{% set version = "v3.1.0" %}
{% set sha256 = "e67527c8dd175f5730ca877aa506bc7aa4178cb0154d5b1a2794e1a484956c83" %}

package:
  name: hhsuite
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/soedinglab/hh-suite/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake
    - make
  host:
    - openmp
    - perl
    - python
  run:
    - openmp
    - python
    - perl

test:
  commands:
    - hhblits -h > /dev/null
    - hhsearch -h > /dev/null
    - hhalign -h > /dev/null

about:
  home: https://github.com/soedinglab/hh-suite
  license: GPLv3
  license_file: LICENSE
  summary: "HH-suite3 for fast remote homology detection and deep protein annotation"
